<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>CQ Clientlib txt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>##.*</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[^#]*</string>
			<key>name</key>
			<string>string.unquoted</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.txt.cq</string>
	<key>uuid</key>
	<string>e1d7a17d-3d1b-42fa-8b47-7b08c012aeae</string>
</dict>
</plist>
